config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :buckets
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Set root to courses index since it's the main feature of our app
  root "courses#index"
  # Triple nest resources to create the desired database hierarchy
  resources :courses do
    resources :sections do
      resources :assignments
    end
  end
  
  # Route a non-RESTful route, enroll
  get 'courses/:id/enroll', to: 'courses#enroll', as: :enroll
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    # Require login to do anything other than view list of courses and
    # to see the basic overview of the course, i.e. no sections
    before_action :authenticate_user!, except: [:index, :show]
    # Require instructor of course to edit or destroy the course
    before_action :require_instructor!, only: [:edit, :update, :destroy]
    # Prevent enrolled people from enrolling again
    # and creating a duplicate enrollment
    before_action :require_unenrolled!, only: [:enroll]
    # Prevent enrollment after the course has started
    before_action :require_has_not_started!, only: [:enroll]

    def index
        @courses = Course.all
    end

    def show
        @course = Course.find(params[:id])
    end

    def new
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        if @course.save
            @course.add_user(current_user, "instructor")
            redirect_to course_path(@course)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        if @course.update(course_params)
            redirect_to course_path(@course)
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        redirect_to root_path, status: :see_other
    end

    def enroll
        @course = Course.find(params[:id])
        @course.add_user(current_user, "student")
        redirect_to course_path(@course)
    end

    private
        def course_params
            params.require(:course).permit(:title, :description, :price, :start_date, :end_date)
        end

        # Makes sure that the course has not started, i.e. that the
        # current date and time is before the course start date and time
        def require_has_not_started!
            @course = Course.find(params[:id])
            unless @course.start_date > DateTime.current
                flash[:error] = "You cannot enroll in a course that has already started."
                redirect_to course_path(@course)
            end
        end

        # Makes sure that the current user is an instructor of the course
        def require_instructor!
            @course = Course.find(params[:id])
            unless @course.check_user_role(current_user) == "instructor"
                flash[:error] = "You must be an instructor of this course to continue."
                redirect_to course_path(@course)
            end
        end

        # Makes sure that the current user is not enrolled in the course
        def require_unenrolled!
            @course = Course.find(params[:id])
            unless @course.check_user_role(current_user) == nil
                flash[:error] = "You are already enrolled in this course."
                redirect_to course_path(@course)
            end
        end
end

app/views/courses/_form.html.erb
<%= form_with model: course do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% course.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% course.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
    <% course.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>    
  </div>

  <div>
    <%= form.label :start_date %><br>
    <%= form.datetime_local_field :start_date %>
    <% course.errors.full_messages_for(:start_date).each do |message| %>
      <div><%= message %></div>
    <% end %>    
  </div>

  <div>
    <%= form.label :end_date %><br>
    <%= form.datetime_local_field :end_date %>
    <% course.errors.full_messages_for(:end_date).each do |message| %>
      <div><%= message %></div>
    <% end %>    
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render "form", course: @course %>

app/views/courses/index.html.erb
<h1>Courses</h1>

<% unless current_user == nil %>
  <h3>Currently Enrolled</h3>
  <ul>
    <% current_user.enrollments.each do |enrollment| %>
      <% @course = Course.find(enrollment.course_id) %>
      <li><%= link_to "#{@course.title}", course_path(@course) %></li>
    <% end %>
  </ul>
<% end %>

<% if Course.where("start_date > ?", DateTime.current).any? %>
  <h3>Available</h3>
  <ul>
    <% @courses.each do |course| %>
      <% if course.start_date > DateTime.current %>
        <li><%= link_to "#{course.title}", course_path(course) %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% if Course.where("start_date <= ?", DateTime.current).any? && Course.where("end_date > ?", DateTime.current).any? %>
  <h3>In-Progress</h3>
  <ul>
    <% @courses.each do |course| %>
      <% if course.start_date <= DateTime.current && course.end_date > DateTime.current %>
        <li><%= link_to "#{course.title}", course_path(course) %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% if Course.where("end_date <= ?", DateTime.current).any? %>
  <h3>Finished</h3>
  <ul>
    <% @courses.each do |course| %>
      <% if course.end_date <= DateTime.current %>
        <li><%= link_to "#{course.title}", course_path(course) %></li>
      <% end %>
    <% end %>
  </ul>
<% end %>

<% unless current_user == nil %>
  <%= link_to "New Course", new_course_path %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render "form", course: @course, :action => "new"  %>

app/views/courses/show.html.erb
<%= link_to "Return to all courses", root_path %>

<h1><%= @course.title %></h1>
<p><%= @course.description %></p>
<p>Price: <%= @course.price %></p>
<p>Starts on: <%= @course.start_date %></p>
<p>Ends on: <%= @course.end_date %></p>

<% current_user_role = @course.check_user_role(current_user) %>
<% unless current_user_role == nil %>
  <% if @course.sections.any? %>
    <h2>Sections</h2>
  <% end %>
  <% @course.sections.each do |section| %>
    <h4>
      <%= section.title %>
    </h4>
    <% section.assignments.each do |assignment| %>
      <%= link_to assignment.title, course_section_assignment_path(:course_id => @course.id, :section_id => section.id, :id => assignment.id) %>
      <br>
    <% end %>
    <% if current_user_role == "instructor" %>
      <%= link_to "Add Assignment", new_course_section_assignment_path(:course_id => @course.id, :section_id => section.id) %>
      <%= link_to "Destroy Section", [section.course, section], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
    <% end %>
  <% end %>

  <% if current_user_role == "instructor" %>
    <h2>Add a section:</h2>
    <%= form_with model: [ @course, @course.sections.build ] do |form| %>
      <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </p>
      <p>
        <%= form.submit %>
      </p>
    <% end %>
  <% end %>
<% end %>

<ul>
  <% if current_user != nil && current_user_role == nil && @course.start_date > DateTime.current%>
    <li><%= link_to "Enroll", enroll_path(@course)%></li>
  <% end %>

  <% if @course.check_user_role(current_user) == "instructor" %>
    <li><%= link_to "Edit Course", edit_course_path(@course) %></li>

    <li><%= link_to "Destroy Course", course_path(@course), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></li>
  <% end %>
</ul>